<a href="https://colab.research.google.com/github/cbonnin88/mes_allocs-ETL/blob/main/Product_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl
import plotly.express as px
from google.cloud import bigquery
from google.colab import auth

# **Authenticate**

In [2]:
auth.authenticate_user()
project_id = 'mes-allocs-analysis'
client = bigquery.Client(project=project_id)

# **Querying the table that I build in dbt**

In [4]:
product_query = """
  SELECT * FROM `mes-allocs-analysis.dbt_mes_allocs.fct_product_events`
"""

df_product = pl.from_pandas(client.query(product_query).to_dataframe())

In [5]:
df_product.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ event_typ ┆ event_at  ┆ device_id ┆ … ┆ gender    ┆ user_stat ┆ subscript ┆ plan_pri │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ ---       ┆ us        ┆ ion_plan  ┆ ce       │
│ str       ┆ ---       ┆ datetime[ ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ μs, UTC]  ┆           ┆   ┆           ┆ str       ┆ str       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ user_6914 ┆ applicati ┆ 2026-01-0 ┆ dev_8929  ┆ … ┆ Female    ┆ Full-time ┆ Free      ┆ 0.0      │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ Employee  ┆           ┆          │
│           ┆ ted       ┆ 00:00:08  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│ user_2843 ┆ applicati ┆ 2026-01-0 ┆ dev_3260  ┆ … ┆ Male      ┆ Job-Seeke ┆ Free      ┆ 0.0      │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ r         ┆           ┆          │
│           ┆ ted       ┆ 00:21:16  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│ user_1190 ┆ applicati ┆ 2026-01-0 ┆ dev_8491  ┆ … ┆ Male      ┆ Job-Seeke ┆ Free      ┆ 0.0      │
│ 9         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ r         ┆           ┆          │
│           ┆ ted       ┆ 00:38:00  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│ user_1173 ┆ applicati ┆ 2026-01-0 ┆ dev_2603  ┆ … ┆ Non-Binar ┆ Job-Seeke ┆ Basic     ┆ 7.99     │
│ 4         ┆ on_submit ┆ 1         ┆           ┆   ┆ y         ┆ r         ┆           ┆          │
│           ┆ ted       ┆ 00:47:21  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
│ user_1311 ┆ applicati ┆ 2026-01-0 ┆ dev_4694  ┆ … ┆ Female    ┆ Job-Seeke ┆ Free      ┆ 0.0      │
│ 1         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ r         ┆           ┆          │
│           ┆ ted       ┆ 00:59:43  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
display(df_product.describe())

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ user_id   ┆ event_typ ┆ event_at  ┆ … ┆ gender    ┆ user_stat ┆ subscript ┆ plan_pri │
│ ---       ┆ ---       ┆ e         ┆ ---       ┆   ┆ ---       ┆ us        ┆ ion_plan  ┆ ce       │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ str       ┆ str       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 600000    ┆ 600000    ┆ 600000    ┆ … ┆ 600000    ┆ 600000    ┆ 600000    ┆ 600000.0 │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ 2026-02-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2.942244 │
│           ┆           ┆           ┆ 5 01:23:4 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 8.920980+ ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:…      ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 4.64316  │
│ min       ┆ user_0    ┆ applicati ┆ 2026-01-0 ┆ … ┆ Female    ┆ Full-time ┆ Basic     ┆ 0.0      │
│           ┆           ┆ on_submit ┆ 1 00:00:0 ┆   ┆           ┆ Employee  ┆           ┆          │
│           ┆           ┆ ted       ┆ 0+00:00   ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ 2026-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.0      │
│           ┆           ┆           ┆ 3 13:51:2 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 2+00:00   ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ null      ┆ null      ┆ 2026-02-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.0      │
│           ┆           ┆           ┆ 5 01:47:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 7+00:00   ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ null      ┆ null      ┆ 2026-03-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 7.99     │
│           ┆           ┆           ┆ 9 13:08:0 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 5+00:00   ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ user_9999 ┆ subscript ┆ 2026-03-3 ┆ … ┆ Non-Binar ┆ Part-time ┆ Premium   ┆ 12.99    │
│           ┆           ┆ ion_upgra ┆ 1 23:59:4 ┆   ┆ y         ┆ Employee  ┆           ┆          │
│           ┆           ┆ ded       ┆ 5+00:00   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# **Metric 1: Retention (Cohort Analysis)**
- I'll group users by their Signup Month and see how many remain active in subsequent months.

In [8]:
# Create Cohorts
cohort_df = df_product.with_columns([
    pl.col('event_at').dt.truncate('1mo').alias('event_month'),
    pl.col('event_at').min().over('user_id').dt.truncate('1mo').alias('cohort_month')
])

display(cohort_df.head())

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ event_typ ┆ event_at  ┆ device_id ┆ … ┆ subscript ┆ plan_pric ┆ event_mon ┆ cohort_m │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ ion_plan  ┆ e         ┆ th        ┆ onth     │
│ str       ┆ ---       ┆ datetime[ ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ μs, UTC]  ┆           ┆   ┆ str       ┆ f64       ┆ datetime[ ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs, UTC]  ┆ [μs,     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ UTC]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ user_6914 ┆ applicati ┆ 2026-01-0 ┆ dev_8929  ┆ … ┆ Free      ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01- │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆           ┆ 1         ┆ 01       │
│           ┆ ted       ┆ 00:00:08  ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00 │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆ UTC       ┆ UTC      │
│ user_2843 ┆ applicati ┆ 2026-01-0 ┆ dev_3260  ┆ … ┆ Free      ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01- │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆           ┆ 1         ┆ 01       │
│           ┆ ted       ┆ 00:21:16  ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00 │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆ UTC       ┆ UTC      │
│ user_1190 ┆ applicati ┆ 2026-01-0 ┆ dev_8491  ┆ … ┆ Free      ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01- │
│ 9         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆           ┆ 1         ┆ 01       │
│           ┆ ted       ┆ 00:38:00  ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00 │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆ UTC       ┆ UTC      │
│ user_1173 ┆ applicati ┆ 2026-01-0 ┆ dev_2603  ┆ … ┆ Basic     ┆ 7.99      ┆ 2026-01-0 ┆ 2026-01- │
│ 4         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆           ┆ 1         ┆ 01       │
│           ┆ ted       ┆ 00:47:21  ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00 │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆ UTC       ┆ UTC      │
│ user_1311 ┆ applicati ┆ 2026-01-0 ┆ dev_4694  ┆ … ┆ Free      ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01- │
│ 1         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆           ┆ 1         ┆ 01       │
│           ┆ ted       ┆ 00:59:43  ┆           ┆   ┆           ┆           ┆ 00:00:00  ┆ 00:00:00 │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆           ┆ UTC       ┆ UTC      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# Calculate months since signup
cohort_df = cohort_df.with_columns(
    ((pl.col('event_month') - pl.col('cohort_month')).dt.total_days() / 30).round(0).cast(pl.Int64).alias('month_number')
)

display(cohort_df.head())

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ event_typ ┆ event_at  ┆ device_id ┆ … ┆ plan_pric ┆ event_mon ┆ cohort_mo ┆ month_nu │
│ ---       ┆ e         ┆ ---       ┆ ---       ┆   ┆ e         ┆ th        ┆ nth       ┆ mber     │
│ str       ┆ ---       ┆ datetime[ ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ μs, UTC]  ┆           ┆   ┆ f64       ┆ datetime[ ┆ datetime[ ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs, UTC]  ┆ μs, UTC]  ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ user_6914 ┆ applicati ┆ 2026-01-0 ┆ dev_8929  ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01-0 ┆ 0        │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ted       ┆ 00:00:08  ┆           ┆   ┆           ┆ 00:00:00  ┆ 00:00:00  ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆ UTC       ┆ UTC       ┆          │
│ user_2843 ┆ applicati ┆ 2026-01-0 ┆ dev_3260  ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01-0 ┆ 0        │
│           ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ted       ┆ 00:21:16  ┆           ┆   ┆           ┆ 00:00:00  ┆ 00:00:00  ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆ UTC       ┆ UTC       ┆          │
│ user_1190 ┆ applicati ┆ 2026-01-0 ┆ dev_8491  ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01-0 ┆ 0        │
│ 9         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ted       ┆ 00:38:00  ┆           ┆   ┆           ┆ 00:00:00  ┆ 00:00:00  ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆ UTC       ┆ UTC       ┆          │
│ user_1173 ┆ applicati ┆ 2026-01-0 ┆ dev_2603  ┆ … ┆ 7.99      ┆ 2026-01-0 ┆ 2026-01-0 ┆ 0        │
│ 4         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ted       ┆ 00:47:21  ┆           ┆   ┆           ┆ 00:00:00  ┆ 00:00:00  ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆ UTC       ┆ UTC       ┆          │
│ user_1311 ┆ applicati ┆ 2026-01-0 ┆ dev_4694  ┆ … ┆ 0.0       ┆ 2026-01-0 ┆ 2026-01-0 ┆ 0        │
│ 1         ┆ on_submit ┆ 1         ┆           ┆   ┆           ┆ 1         ┆ 1         ┆          │
│           ┆ ted       ┆ 00:59:43  ┆           ┆   ┆           ┆ 00:00:00  ┆ 00:00:00  ┆          │
│           ┆           ┆ UTC       ┆           ┆   ┆           ┆ UTC       ┆ UTC       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# Aggregate
cohort_pivot = cohort_df.group_by(['cohort_month','month_number']).agg(
    pl.col('user_id').n_unique().alias('active_users')
).sort(['cohort_month','month_number'])

display(cohort_pivot)

shape: (3, 3)
┌─────────────────────────┬──────────────┬──────────────┐
│ cohort_month            ┆ month_number ┆ active_users │
│ ---                     ┆ ---          ┆ ---          │
│ datetime[μs, UTC]       ┆ i64          ┆ u32          │
╞═════════════════════════╪══════════════╪══════════════╡
│ 2026-01-01 00:00:00 UTC ┆ 0            ┆ 15000        │
│ 2026-01-01 00:00:00 UTC ┆ 1            ┆ 15000        │
│ 2026-01-01 00:00:00 UTC ┆ 2            ┆ 15000        │
└─────────────────────────┴──────────────┴──────────────┘

In [12]:
fig_cohort = px.imshow(
    cohort_pivot.to_pandas().pivot(index='cohort_month',columns='month_number',values='active_users'),
    labels=dict(x='Months Since Signup',y='Cohort Month',color='Active Users'),
    title='Users Retention Cohort',
    color_continuous_scale='Viridis'
)

fig_cohort.show()

# **Metric 2: Conversion Funnel (by Device)**
- Visualizing the drop-off

In [13]:
funnel_data = df_product.group_by(['device_type','event_type']).agg(
    pl.col('user_id').n_unique().alias('user_count')
).filter(pl.col('event_type').is_in(['simulationi_started','simulation_completed','application_submitted']))

display(funnel_data)

shape: (6, 3)
┌─────────────┬───────────────────────┬────────────┐
│ device_type ┆ event_type            ┆ user_count │
│ ---         ┆ ---                   ┆ ---        │
│ str         ┆ str                   ┆ u32        │
╞═════════════╪═══════════════════════╪════════════╡
│ Mobile      ┆ simulation_completed  ┆ 8224       │
│ Mobile      ┆ application_submitted ┆ 7894       │
│ Desktop     ┆ application_submitted ┆ 5736       │
│ Tablet      ┆ simulation_completed  ┆ 786        │
│ Desktop     ┆ simulation_completed  ┆ 5950       │
│ Tablet      ┆ application_submitted ┆ 760        │
└─────────────┴───────────────────────┴────────────┘

In [15]:
fig_funnel = px.funnel(
    funnel_data.to_pandas(),
    x='user_count',
    y='event_type',
    color='device_type',
    title='Product Conversion Funnel by Device',
    labels={'user_count':'Number of Users','device_type':'Device Type'}
)

fig_funnel.show()

# **Metrics 3: Feature Adoption (Benefit vs. Status)**
- Which user statuses (Job-Seekers, etc.) are actually selecting benefits?

In [31]:
adoption = df_product.filter(pl.col('event_type') == "benefit_selected") \
                      .group_by(['user_status','subscription_plan']) \
                      .agg(pl.len().alias('selections'))


display(adoption)

shape: (9, 3)
┌────────────────────┬───────────────────┬────────────┐
│ user_status        ┆ subscription_plan ┆ selections │
│ ---                ┆ ---               ┆ ---        │
│ str                ┆ str               ┆ u32        │
╞════════════════════╪═══════════════════╪════════════╡
│ Job-Seeker         ┆ Free              ┆ 25235      │
│ Full-time Employee ┆ Free              ┆ 28244      │
│ Part-time Employee ┆ Free              ┆ 9247       │
│ Full-time Employee ┆ Basic             ┆ 8284       │
│ Job-Seeker         ┆ Premium           ┆ 3715       │
│ Job-Seeker         ┆ Basic             ┆ 6884       │
│ Part-time Employee ┆ Premium           ┆ 1243       │
│ Full-time Employee ┆ Premium           ┆ 4284       │
│ Part-time Employee ┆ Basic             ┆ 2572       │
└────────────────────┴───────────────────┴────────────┘

In [38]:
fig_feature = px.bar(
    adoption.to_pandas(),
    x='user_status',
    y='selections',
    color='subscription_plan',
    barmode = 'group',
    title='Feature Adoption by User Status',
    color_discrete_sequence=px.colors.sequential.Viridis_r,
    labels= {'selections':'Selection','user_status':'User Status','subscription_plan':'Subscription Plan'}
)

fig_feature.show()

# **Metric 4: Revenue & ARPU**
- Average Revenue Per User by Gender and Status

In [19]:
revenue = df_product.group_by(['user_status','gender']).agg([
    pl.col('plan_price').mean().round(2).alias('arpu')
])

display(revenue)

shape: (9, 3)
┌────────────────────┬────────────┬──────┐
│ user_status        ┆ gender     ┆ arpu │
│ ---                ┆ ---        ┆ ---  │
│ str                ┆ str        ┆ f64  │
╞════════════════════╪════════════╪══════╡
│ Job-Seeker         ┆ Male       ┆ 2.88 │
│ Full-time Employee ┆ Non-Binary ┆ 2.92 │
│ Part-time Employee ┆ Male       ┆ 2.76 │
│ Part-time Employee ┆ Non-Binary ┆ 3.49 │
│ Job-Seeker         ┆ Non-Binary ┆ 2.96 │
│ Job-Seeker         ┆ Female     ┆ 2.93 │
│ Part-time Employee ┆ Female     ┆ 2.95 │
│ Full-time Employee ┆ Female     ┆ 2.98 │
│ Full-time Employee ┆ Male       ┆ 3.01 │
└────────────────────┴────────────┴──────┘

In [29]:
fig_revenue = px.sunburst(
    revenue.to_pandas(),
    path=['user_status','gender'],
    values = 'arpu',
    color = 'arpu',
    title = 'ARPU Distribution (Status & Gender)',
    color_continuous_scale='Viridis_r'
)

fig_revenue.update_layout(showlegend=False, coloraxis_showscale=False)
fig_revenue.show()